/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesAiAndAutomationRouteImport } from './routes/services/ai-and-automation'
import { Route as ServicesBrandDesignRouteImport } from './routes/services/brand-design'
import { Route as ServicesMarketingAndGrowthRouteImport } from './routes/services/marketing-and-growth'
import { Route as ServicesMediaProductionRouteImport } from './routes/services/media-production'
import { Route as ServicesSoftwareSolutionsRouteImport } from './routes/services/software-solutions'
import { Route as ServicesWebAndAppDevelopmentRouteImport } from './routes/services/web-and-app-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAndAutomationRoute = ServicesAiAndAutomationRouteImport.update({
  id: '/services/ai-and-automation',
  path: '/services/ai-and-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrandDesignRoute = ServicesBrandDesignRouteImport.update({
  id: '/services/brand-design',
  path: '/services/brand-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingAndGrowthRoute =
  ServicesMarketingAndGrowthRouteImport.update({
    id: '/services/marketing-and-growth',
    path: '/services/marketing-and-growth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMediaProductionRoute = ServicesMediaProductionRouteImport.update({
  id: '/services/media-production',
  path: '/services/media-production',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareSolutionsRoute =
  ServicesSoftwareSolutionsRouteImport.update({
    id: '/services/software-solutions',
    path: '/services/software-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebAndAppDevelopmentRoute =
  ServicesWebAndAppDevelopmentRouteImport.update({
    id: '/services/web-and-app-development',
    path: '/services/web-and-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-and-automation': typeof ServicesAiAndAutomationRoute
  '/services/brand-design': typeof ServicesBrandDesignRoute
  '/services/marketing-and-growth': typeof ServicesMarketingAndGrowthRoute
  '/services/media-production': typeof ServicesMediaProductionRoute
  '/services/software-solutions': typeof ServicesSoftwareSolutionsRoute
  '/services/web-and-app-development': typeof ServicesWebAndAppDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-and-automation': typeof ServicesAiAndAutomationRoute
  '/services/brand-design': typeof ServicesBrandDesignRoute
  '/services/marketing-and-growth': typeof ServicesMarketingAndGrowthRoute
  '/services/media-production': typeof ServicesMediaProductionRoute
  '/services/software-solutions': typeof ServicesSoftwareSolutionsRoute
  '/services/web-and-app-development': typeof ServicesWebAndAppDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-and-automation': typeof ServicesAiAndAutomationRoute
  '/services/brand-design': typeof ServicesBrandDesignRoute
  '/services/marketing-and-growth': typeof ServicesMarketingAndGrowthRoute
  '/services/media-production': typeof ServicesMediaProductionRoute
  '/services/software-solutions': typeof ServicesSoftwareSolutionsRoute
  '/services/web-and-app-development': typeof ServicesWebAndAppDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/gallery'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/services/$slug'
    | '/services/ai-and-automation'
    | '/services/brand-design'
    | '/services/marketing-and-growth'
    | '/services/media-production'
    | '/services/software-solutions'
    | '/services/web-and-app-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/gallery'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/services/$slug'
    | '/services/ai-and-automation'
    | '/services/brand-design'
    | '/services/marketing-and-growth'
    | '/services/media-production'
    | '/services/software-solutions'
    | '/services/web-and-app-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/gallery'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/services/$slug'
    | '/services/ai-and-automation'
    | '/services/brand-design'
    | '/services/marketing-and-growth'
    | '/services/media-production'
    | '/services/software-solutions'
    | '/services/web-and-app-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GalleryRoute: typeof GalleryRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesAiAndAutomationRoute: typeof ServicesAiAndAutomationRoute
  ServicesBrandDesignRoute: typeof ServicesBrandDesignRoute
  ServicesMarketingAndGrowthRoute: typeof ServicesMarketingAndGrowthRoute
  ServicesMediaProductionRoute: typeof ServicesMediaProductionRoute
  ServicesSoftwareSolutionsRoute: typeof ServicesSoftwareSolutionsRoute
  ServicesWebAndAppDevelopmentRoute: typeof ServicesWebAndAppDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-and-automation': {
      id: '/services/ai-and-automation'
      path: '/services/ai-and-automation'
      fullPath: '/services/ai-and-automation'
      preLoaderRoute: typeof ServicesAiAndAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/brand-design': {
      id: '/services/brand-design'
      path: '/services/brand-design'
      fullPath: '/services/brand-design'
      preLoaderRoute: typeof ServicesBrandDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing-and-growth': {
      id: '/services/marketing-and-growth'
      path: '/services/marketing-and-growth'
      fullPath: '/services/marketing-and-growth'
      preLoaderRoute: typeof ServicesMarketingAndGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/media-production': {
      id: '/services/media-production'
      path: '/services/media-production'
      fullPath: '/services/media-production'
      preLoaderRoute: typeof ServicesMediaProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-solutions': {
      id: '/services/software-solutions'
      path: '/services/software-solutions'
      fullPath: '/services/software-solutions'
      preLoaderRoute: typeof ServicesSoftwareSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-and-app-development': {
      id: '/services/web-and-app-development'
      path: '/services/web-and-app-development'
      fullPath: '/services/web-and-app-development'
      preLoaderRoute: typeof ServicesWebAndAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  GalleryRoute: GalleryRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesAiAndAutomationRoute: ServicesAiAndAutomationRoute,
  ServicesBrandDesignRoute: ServicesBrandDesignRoute,
  ServicesMarketingAndGrowthRoute: ServicesMarketingAndGrowthRoute,
  ServicesMediaProductionRoute: ServicesMediaProductionRoute,
  ServicesSoftwareSolutionsRoute: ServicesSoftwareSolutionsRoute,
  ServicesWebAndAppDevelopmentRoute: ServicesWebAndAppDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
